---
- hosts: all
  become: true
  tasks:
    - name: Install latest version of Apache
      apt: 
        name: apache2 
        update_cache: yes 
        state: latest
    - name: copy code
      git:
        repo: https://github.com/Paix726/images.git
        dest: /var/www/html
  handlers:
    - name: Restart apache
      systemd:
        name: apache
        state: started
        enabled: yes
      
