---
- hosts: all
  become: true
  tasks:

   - name: Upgrade all packages on servers
     apt:
         upgrade: dist
         force_apt_get: yes

   - name: Set hostname
     hostname:
         name: pooja.san.com

   - name: Install Common packages
     apt:
         name:
           - vim
           - wget
         state: latest

   - name: install ElasticSearch package
     shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

   - name: check package list
     shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

   - name: update cache and ignore errors in case of problems
     become: yes
     apt: update_cache=yes
     ignore_errors: yes

   - name: install elasticsearch
     become: yes
     apt:
        name: elasticsearch
        state: present
        update_cache: yes
     notify:
         - Start Elasticsearch
         - Enable Elasticsearch

  handlers:
     - name: Start Elasticsearch
       systemd:
         name: elasticsearch
         state: started

     - name: Enable Elasticsearch
       systemd:
         name: elasticsearch
         enabled: yes       
